SecureDevAsgn2-master/Assignment2_SecureDev/webThread/threadApp/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from . import views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = 'threadApp'

urlpatterns = [
    url(r'^$', views.index_v, name='index'),
    url(r'^details/(?P<id>\d+)/$', views.details_v, name='details'),
    url(r'^signup/', views.signup_v, name='signup'),
    url(r'^login/', views.login_v, name='login'),
    url(r'^logout/', views.logout_v, name='logout'),
    url(r'^profile/', views.profile_v, name='profile'),
    url(r'^updateProf/', views.updateProfile_v, name='updateProf'),
    url(r'^deleteProf/', views.deleteProfile_v, name='deleteProf'),
    #url(r'^reset-password/$', PasswordResetView.as_view(success_url=reverse_lazy('threadApp:password_reset_done')), name='reset_password'),
    #url(r'^reset-password/done/$', PasswordResetDoneView.as_view(), name='password_reset_done'),
    #url(r'^reset-password/confirm/(?P<uid64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^createThread/', views.insertThread_v, name='createThread'),
    url(r'^uploadThread/', views.uploadThread_v, name='uploadThread'),
    url(r'^usersThread/', views.usersThread_v, name='usersThread'),
    url(r'^threadEdit/(?P<id>\d+)/$', views.threadEdit_v, name='threadEdit'),
    url(r'^threadDelete/(?P<id>\d+)/$', views.threadDelete_v, name='threadDelete'),
    url(r'^threadDownload/(?P<id>\d+)/$', views.threadDownload_v, name='threadDownload'),
]

SecureDevAsgn2-master/Assignment2_SecureDev/webThread/webThread/urls.py
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
    path('', include('threadApp.urls')),
    path('admin/', admin.site.urls),
    path('threadApp/', include('threadApp.urls'))
]

SecureDevAsgn2-master/Assignment2_SecureDev/webThread/threadApp/models.py
from django.db import models
from datetime import datetime
from pytz import timezone
from django.conf import settings

expire_time = [
    ('10 mins', '10 Minutes'),
    ('1 hr', '1 Hour'),
    ('1 day', '1 Day'),
    ('1 week', '1 Week'),
]

expose = [
    ('public', 'Public'),
    ('private', 'Private'),
]


class Threads(models.Model):
    thread_Owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,  default=1, related_name='thread_Owner')
    thread_Name = models.CharField(max_length=200)
    thread_Body = models.TextField()
    thread_Exposer = models.CharField(default='public', max_length=200)
    thread_Expire = models.CharField(default='10 mins', max_length=200)
    thread_TillExpire = models.CharField(default='', max_length=200)
    thread_Share = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='thread_Share')
    created_At = models.DateTimeField(default=datetime.now().replace(tzinfo=timezone('UTC')))
    def __str__(self):
        return self.thread_Name
    class Meta:
        verbose_name_plural = "Threads"

SecureDevAsgn2-master/Assignment2_SecureDev/webThread/threadApp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from datetime import datetime

from .models import Threads

class UniqueUserEmailField(forms.EmailField):
    def validate(self, value):
        super(forms.EmailField, self).validate(value)
        try:
            User.objects.get(email = value)
            raise forms.ValidationError("Email already exists")
        except User.MultipleObjectsReturned:
            raise forms.ValidationError("Email already exists")
        except User.DoesNotExist:
            pass


class ExtendedUserCreationForm(UserCreationForm):  
    username = forms.CharField(required = False, max_length = 30)
    email = UniqueUserEmailField(required = True, label = 'Email address')
    first_name = forms.CharField(required = True, max_length = 30)
    last_name = forms.CharField(required = True, max_length = 30)
        
    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit)
        if user:
            user.email = self.cleaned_data['email']
            user.first_name = self.cleaned_data['first_name']
            user.last_name = self.cleaned_data['last_name']
            user.set_password(self.cleaned_data['password1'])
            if commit:
                user.save()
        return user
    
class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = {
            'first_name',
            'last_name',
            'email'
        }

expire_time = [
    ('10 mins', '10 Minutes'),
    ('1 hr', '1 Hour'),
    ('1 day', '1 Day'),
    ('1 week', '1 Week'),
]

expose = [
    ('public', 'Public'),
    ('private', 'Private'),
]

class CreateThreadForm(forms.ModelForm):

    class Meta:
        model = Threads
        fields = ['thread_Name', 'thread_Body', 'thread_Exposer', 'thread_Expire', 'thread_Share', 'created_At']
        widgets = {
            'thread_Body' : forms.Textarea,
            'thread_Exposer' : forms.Select(choices=expose),
            'thread_Expire' : forms.Select(choices=expire_time)
        }

SecureDevAsgn2-master/Assignment2_SecureDev/webThread/threadApp/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth import login, logout
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import csv

from pytz import timezone
from datetime import datetime, timedelta
from .models import Threads
from .forms import EditProfileForm, CreateThreadForm, ExtendedUserCreationForm

def index_v(request):
    threads_list = Threads.objects.all().order_by('-id')
    query = request.GET.get("search_Post")
    if query:
        threads_list = threads_list.filter(thread_Name__icontains=query)
    paginator = Paginator(threads_list, 10)
    page = request.GET.get('page')
    try:
        threads = paginator.page(page)
    except PageNotAnInteger:
        threads = paginator.page(1)
    except EmptyPage:
        threads = paginator.page(paginator.num_pages)

    delta = 0
    for thread in threads:
        if thread.thread_Expire == "10 mins":
            delta = timedelta(minutes=10)
        elif thread.thread_Expire == "1 hr":
            delta = timedelta(hours=1)
        elif thread.thread_Expire == "1 day":
            delta = timedelta(days=1)
        elif thread.thread_Expire == "1 week":
            delta = timedelta(weeks=1)
        
        d = thread.created_At
        d1 = d+delta

        print(d)
        print(d1)

        expireTime = d1-datetime.now().replace(tzinfo=timezone('UTC'))

        t = Threads.objects.get(id=thread.id)
        t.thread_TillExpire = str(expireTime)
        t.save()

        if d1 < datetime.now().replace(tzinfo=timezone('UTC')):
            Threads.objects.get(id=thread.id).delete()
        else:
            print("Not Expired")

    context = {
        'title': 'Latest Threads',
        'threads': threads
    }

    return render(request, 'threadApp/main.html', context)

def usersThread_v(request):
    threads_list = Threads.objects.filter(thread_Owner=request.user)
    query = request.GET.get("search_Post")
    if query:
        threads_list = threads_list.filter(thread_Name__icontains=query)

    delta = 0
    for thread in threads_list:
        if thread.thread_Expire == "10 mins":
            delta = timedelta(minutes=10)
        elif thread.thread_Expire == "1 hr":
            delta = timedelta(hours=1)
        elif thread.thread_Expire == "1 day":
            delta = timedelta(days=1)
        elif thread.thread_Expire == "1 week":
            delta = timedelta(weeks=1)
        
        d = thread.created_At
        d1 = d+delta

        expireTime = d1-datetime.now().replace(tzinfo=timezone('UTC'))

        t = Threads.objects.get(id=thread.id)
        t.thread_TillExpire = str(expireTime)
        t.save()

        if d1 < datetime.now().replace(tzinfo=timezone('UTC')):
            Threads.objects.get(id=thread.id).delete()

    context = {
        'title': 'Your Created Threads',
        'threads': threads_list
    }

    return render(request, 'threadApp/usersThread.html', context)

def insertThread_v(request):
    if request.method == 'POST':
        form = CreateThreadForm(request.POST)
        if form.is_valid():
            newThread = form.save(commit=False)
            newThread.thread_Owner = request.user
            newThread.save()
            return redirect('/threadApp/details/' + str(newThread.id))
    else:
        form = CreateThreadForm()

    context = {
        'title': 'Create A Thread',
        'form': form
    }
    
    return render(request, 'threadApp/createThread.html', context)

def uploadThread_v(request):
    if request.method == 'POST' and request.FILES['threadDoc']:
        myfile = request.FILES['threadDoc']
        lines = myfile.read().decode("utf-8").split(", ")
        form = CreateThreadForm(instance=Threads(thread_Name=lines[0], thread_Body=lines[1]))
    else:
        form = CreateThreadForm()
        form.fields['thread_Name'].widget.attrs['readonly'] = True
        form.fields['thread_Body'].widget.attrs['readonly'] = True
        form.fields['thread_Exposer'].widget.attrs['disabled'] = True
        form.fields['thread_Expire'].widget.attrs['disabled'] = True
        form.fields['thread_Share'].widget.attrs['disabled'] = True
        form.fields['created_At'].widget.attrs['readonly'] = True
        
    context = {
        'title': 'Upload A File',
        'form': form,
        'info': 'File should be a .txt file and contents should be in format(ThreadName, ThreadBody)'
    }

    return render(request, 'threadApp/uploadFile.html', context)

def details_v(request, id):
    thread = Threads.objects.get(id=id)

    context = {
        'thread': thread
    }

    return render(request, 'threadApp/details.html', context)

def threadEdit_v(request, id):
    thread = Threads.objects.get(id=id)

    if request.method == "POST":
        form = CreateThreadForm(request.POST, instance=thread)
        if form.is_valid():
            thread = form.save(commit=False)
            thread.thread_Owner = request.user
            thread.save()
            return redirect('threadApp:usersThread')
    else:
        form = CreateThreadForm(instance=thread)

    context = {
        'title': 'Edit Thread',
        'form': form,
        'thread': thread
    }

    return render(request, 'threadApp/editThread.html', context)

def threadDelete_v(request, id):
    thread = Threads.objects.get(id=id)
    thread.delete()
    return redirect('threadApp:usersThread')

def threadDownload_v(request, id):
    thread = Threads.objects.get(id=id)

    filename = str(thread.id) + ".txt"
    response = HttpResponse(content_type='text/plain')
    response['Content-Disposition'] = 'attachment; filename={0}'.format(filename)

    writer = csv.writer(response)
    writer.writerow([thread.thread_Name])
    writer.writerow([thread.thread_Owner])
    writer.writerow([thread.thread_Body])
    writer.writerow([thread.created_At])

    return response

def signup_v(request):
    if request.method == 'POST':
        form = ExtendedUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('threadApp:index')
    else:
        form = ExtendedUserCreationForm()

    context = {
        'title': 'Signup',
        'form': form
    }
    
    return render(request, 'threadApp/signup.html', context)

def login_v(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('threadApp:index')
    else:
        form = AuthenticationForm()

    context = {
        'title': 'Login',
        'form': form
    }

    return render(request, 'threadApp/login.html', context)

def logout_v(request):
    if request.method == 'POST':
        logout(request)
        return redirect('threadApp:index')

def profile_v(request):

    context = {
        'title': 'Profile',
        'user': request.user
    }

    return render(request, 'threadApp/profile.html', context)

def updateProfile_v(request):
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('threadApp:profile')
    else:
        form = EditProfileForm(instance=request.user)

    context = {
        'title': 'Update Profile',
        'form': form
    }

    return render(request, 'threadApp/updateProf.html', context)

def deleteProfile_v(request):
    user = request.user
    user.delete()
    return redirect('threadApp:index')

SecureDevAsgn2-master/Assignment2_SecureDev/webThread/threadApp/templates/threadApp/createThread.html
{% extends 'threadApp/layout.html' %}

{% block content %}
<h2 style="text-align: center">{{title}}</h2>
<form class="site-form" action="{% url 'threadApp:createThread' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
<a href="/threadApp/">Back</a>
{% endblock %}

SecureDevAsgn2-master/Assignment2_SecureDev/webThread/threadApp/templates/threadApp/details.html
{% extends 'threadApp/layout.html' %}

{% block content %}
<h2 style="text-align: center">{{thread.thread_Name}}</h2>
<h3>Owner: {{thread.thread_Owner}}</h3>
<h3>Details: {{thread.thread_Body}}</h3>
<h3>Created At: {{thread.created_At}}</h3>
<a href="/threadApp/">Back</a>
{% endblock %}

SecureDevAsgn2-master/Assignment2_SecureDev/webThread/threadApp/templates/threadApp/editThread.html
{% extends 'threadApp/layout.html' %}

{% block content %}
<h2 style="text-align: center">{{title}}</h2>
<form class="site-form" action="{% url 'threadApp:threadEdit' id=thread.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
<a href="/threadApp/usersThread/">Back</a>
{% endblock %}

SecureDevAsgn2-master/Assignment2_SecureDev/webThread/threadApp/templates/threadApp/layout.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Thread Application</title>
</head>

<body>
    <div>
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

SecureDevAsgn2-master/Assignment2_SecureDev/webThread/threadApp/templates/threadApp/main.html
{% extends 'threadApp/layout.html' %}

{% block content %}

<h2 style="text-align: center">{{title}}</h2>

{% if user.is_authenticated %}

<h3 style="text-align: right">
    Welcome: {{ user.username }}
    <a href="/threadApp/profile/">Account Settings</a>
    <form action="{% url 'threadApp:logout' %}" method="POST">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
</h3>

<form action="" method="GET">
    Search: <input type="text" name="search_Post" placeholder="search..." value='{{ request.GET.search_Post }}'>
    <input type="submit" value="Submit">
</form>

<a href="/threadApp/createThread/">Create Thread</a>
<a href="/threadApp/uploadThread">Upload Thread</a>
<a href="/threadApp/usersThread/">All {{ user.username }} Threads</a>

<ul>
    {% for thread in threads %}
    {% if thread.thread_Exposer == "public" %}
    <li><i>Expires in {{thread.thread_TillExpire}}</i> <a href="/threadApp/details/{{thread.id}}">{{thread.thread_Name}}</a></li>
    {% endif %}
    {% endfor %}
</ul>

<div class="pagination">
    <span class="step-links">
        {% if threads.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ threads.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ threads.number }} of {{ threads.paginator.num_pages }}.
        </span>

        {% if threads.has_next %}
        <a href="?page={{ threads.next_page_number }}">next</a>
        <a href="?page={{ threads.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% else %}

<h3 style="text-align: right"><a href="/threadApp/signup">Register</a> <a href="/threadApp/login">Login</a></h3>

<ul>
    {% for thread in threads %}
    {% if thread.thread_Exposer == "public" %}
    <li><a href="/threadApp/details/{{thread.id}}">{{thread.thread_Name}}</a></li>
    {% endif %}
    {% endfor %}
</ul>

<div class="pagination">
    <span class="step-links">
        {% if threads.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ threads.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ threads.number }} of {{ threads.paginator.num_pages }}.
        </span>

        {% if threads.has_next %}
        <a href="?page={{ threads.next_page_number }}">next</a>
        <a href="?page={{ threads.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endif %}

{% endblock %}

SecureDevAsgn2-master/Assignment2_SecureDev/webThread/threadApp/templates/threadApp/profile.html
{% extends 'threadApp/layout.html' %}

{% block content %}
<h2 style="text-align: center">{{title}}</h2>
<h3>Username: {{user.username}}</h3>
<h3>First Name: {{user.first_name}}</h3>
<h3>Last Name: {{user.last_name}}</h3>
<h3>Email Address: {{user.email}}</h3>
<a href="/threadApp/updateProf/">Update Profile</a>
<a href="/threadApp/deleteProf/">Delete Profile</a>
<a href="/threadApp/">Back</a>
{% endblock %}

SecureDevAsgn2-master/Assignment2_SecureDev/webThread/threadApp/templates/threadApp/signup.html
{% extends 'threadApp/layout.html' %}

{% block content %}
<h2 style="text-align: center">{{title}}</h2>
<form class="site-form" action="{% url 'threadApp:signup' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Signup">
</form>
<a href="/threadApp/">Back</a>
{% endblock %}

SecureDevAsgn2-master/Assignment2_SecureDev/webThread/threadApp/templates/threadApp/updateProf.html
{% extends 'threadApp/layout.html' %}

{% block content %}
<h2 style="text-align: center">{{title}}</h2>
<form class="site-form" action="{% url 'threadApp:updateProf' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
<a href="/threadApp/profile/">Back</a>
{% endblock %}

SecureDevAsgn2-master/Assignment2_SecureDev/webThread/threadApp/templates/threadApp/usersThread.html
{% extends 'threadApp/layout.html' %}

{% block content %}
<h2 style="text-align: center">{{title}}</h2>

<form action="" method="GET">
    Search: <input type="text" name="search_Post" placeholder="search..." value='{{ request.GET.search_Post }}'>
    <input type="submit" value="Submit">
</form>

<h3>Public Posts</h3>
<ul>
    {% for thread in threads %}
    {% if thread.thread_Exposer == "public" %}
    <li>
        <i>Expires in {{thread.thread_TillExpire}}</i>
        <a href="/threadApp/details/{{thread.id}}">{{thread.thread_Name}}</a>
        <a href="/threadApp/threadEdit/{{thread.id}}">Edit</a>
        <a href="/threadApp/threadDelete/{{thread.id}}">Delete</a>
        <a href="/threadApp/threadDownload/{{thread.id}}">Download Thread</a>
    </li>
    {% endif %}
    {% endfor %}
</ul>

<h3>Private Posts</h3>
<ul>
    {% for thread in threads %}
    {% if thread.thread_Exposer == "private" %}
    <li>
        <a href="/threadApp/details/{{thread.id}}">{{thread.thread_Name}}</a>
        <a href="/threadApp/threadEdit/{{thread.id}}">Edit</a>
        <a href="/threadApp/threadDelete/{{thread.id}}">Delete</a>
        <a href="/threadApp/threadDownload/{{thread.id}}">Download Thread</a>
    </li>
    {% endif %}
    {% endfor %}
</ul>

<a href="/threadApp/">Back</a>

{% endblock %}