Assignment2_SecureDev/webThread/threadApp/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = 'threadApp'

urlpatterns = [
    url(r'^$', views.index_v, name='index'),
    url(r'^details/(?P<id>\d+)/$', views.details_v, name='details'),
    url(r'^signup/', views.signup_v, name='signup'),
    url(r'^login/', views.login_v, name='login'),
    url(r'^accounts/login/', views.login_v, name='login'),
    url(r'^logout/', views.logout_v, name='logout'),
    url(r'^profile/', views.profile_v, name='profile'),
    url(r'^updateProf/', views.updateProfile_v, name='updateProf'),
    url(r'^deleteProf/', views.deleteProfile_v, name='deleteProf'),
    #url(r'^reset-password/$', PasswordResetView.as_view(success_url=reverse_lazy('threadApp:password_reset_done')), name='reset_password'),
    #url(r'^reset-password/done/$', PasswordResetDoneView.as_view(), name='password_reset_done'),
    #url(r'^reset-password/confirm/(?P<uid64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^createThread/', views.insertThread_v, name='createThread'),
    url(r'^uploadThread/', views.uploadThread_v, name='uploadThread'),
    url(r'^usersThread/', views.usersThread_v, name='usersThread'),
    url(r'^threadEdit/(?P<id>\d+)/$', views.threadEdit_v, name='threadEdit'),
    url(r'^threadDelete/(?P<id>\d+)/$', views.threadDelete_v, name='threadDelete'),
    url(r'^threadDownload/(?P<id>\d+)/$', views.threadDownload_v, name='threadDownload'),
]

Assignment2_SecureDev/webThread/threadApp/templates/threadApp/createThread.html
{% extends 'threadApp/layout.html' %}
{% block content %}
<h2 style="text-align: center">{{title}}</h2>
<form class="site-form" action="{% url 'threadApp:createThread' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
<a href="/threadApp/">Back</a>
{% endblock %}

Assignment2_SecureDev/webThread/threadApp/templates/threadApp/layout.html
<html lang="en">

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Thread Application</title>
</head>

<body>
    <hr>
    <div>
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

Assignment2_SecureDev/webThread/threadApp/templates/threadApp/login.html
{% extends 'threadApp/layout.html' %}

{% block content %}
<h2 style="text-align: center">{{title}}</h2>
<form class="site-form" action="{% url 'threadApp:login' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
</form>
<a href="/threadApp/password_reset/">Forgot Password! Reset NOW!</a>
<a href="/threadApp/">Back</a>
{% endblock %}

Assignment2_SecureDev/webThread/threadApp/templates/threadApp/main.html
{% extends 'threadApp/layout.html' %}

{% block content %}

<U><h2 style="text-align: center">{{title}}</h2></U>
<hr>

{% if user.is_authenticated %}

<h3 style="text-align: left">
    Welcome: {{ user.username }}
</h3>
<p align="left">
    <a href="/threadApp/profile/">Account Settings</a>
</p>
    <form action="{% url 'threadApp:logout' %}" method="POST">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>

<hr>
<form action="" method="GET">
    Search: <input type="text" name="search_Post" placeholder="search..." value='{{ request.GET.search_Post }}'>
    <input type="submit" value="Submit">
</form>

<ul>
    <li><a href="/threadApp/createThread/">Create Thread</a> </li>
    <li><a href="/threadApp/uploadThread">Upload Thread</a> </li>
    <li><a href="/threadApp/usersThread/">All {{ user.username }} Threads</a> </li>
</ul>
<hr>
<h4> <u> Public Posts </u> </h4> 
<ul>
    {% for thread in threads %}
    {% if thread.thread_Exposer == "public" %}
    <li><i>Expires in {{thread.thread_TillExpire}}</i> <a href="/threadApp/details/{{thread.id}}">{{thread.thread_Name}}</a></li>
    {% endif %}
    {% endfor %}
</ul>

<div class="pagination">
    <span class="step-links">
        {% if threads.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ threads.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ threads.number }} of {{ threads.paginator.num_pages }}.
        </span>

        {% if threads.has_next %}
        <a href="?page={{ threads.next_page_number }}">next</a>
        <a href="?page={{ threads.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% else %}
<hr>

<h3 style="text-align: left">
        Welcome: Guest
</h3>
<p> Hi, Try out the pasting website. Login or Register using the link below:</p>
<h5 style="text-align: left"><a href="/threadApp/signup">Register</a> 
<br>
<a href="/threadApp/login">Login</a></h5>

<hr><hr>
<h4> <u> Public Posts </u> </h4> 
<ul>
    {% for thread in threads %}
    {% if thread.thread_Exposer == "public" %}
    <li><a href="/threadApp/details/{{thread.id}}">{{thread.thread_Name}}</a></li>
    {% endif %}
    {% endfor %}
</ul>

<div class="pagination">
    <span class="step-links">
        {% if threads.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ threads.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ threads.number }} of {{ threads.paginator.num_pages }}.
        </span>

        {% if threads.has_next %}
        <a href="?page={{ threads.next_page_number }}">next</a>
        <a href="?page={{ threads.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endif %}

{% endblock %}

Assignment2_SecureDev/webThread/threadApp/templates/threadApp/uploadFile.html
{% extends 'threadApp/layout.html' %}

{% block content %}
<h2 style="text-align: center">{{title}}</h2>
<form class="site-form" action="{% url 'threadApp:uploadThread' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="threadDoc">
    <input type="submit" value="Upload">
</form>
<h4>{{info}}</h4>
<form class="site-form" action="{% url 'threadApp:createThread' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
<a href="/threadApp/">Back</a>
{% endblock %}

Assignment2_SecureDev/webThread/threadApp/templates/threadApp/usersThread.html
{% extends 'threadApp/layout.html' %}

{% block content %}
<h2 style="text-align: center">{{title}}</h2>

<form action="" method="GET">
    Search: <input type="text" name="search_Post" placeholder="search..." value='{{ request.GET.search_Post }}'>
    <input type="submit" value="Submit">
</form>
<hr>
<h3>Public Posts</h3>
<ul>
    {% for thread in threads %}
    {% if thread.thread_Exposer == "public" %}
    <li>
        <i>Expires in {{thread.thread_TillExpire}}</i>
        <a href="/threadApp/details/{{thread.id}}">{{thread.thread_Name}}</a>
        <a href="/threadApp/threadEdit/{{thread.id}}">Edit</a>
        <a href="/threadApp/threadDelete/{{thread.id}}">Delete</a>
        <a href="/threadApp/threadDownload/{{thread.id}}">Download Thread</a>
    </li>
    {% endif %}
    {% endfor %}
</ul>
<hr>
<h3>Private Posts</h3>
<ul>
    {% for thread in threads %}
    {% if thread.thread_Exposer == "private" %}
    <li>
        <a href="/threadApp/details/{{thread.id}}">{{thread.thread_Name}}</a>
        <a href="/threadApp/threadEdit/{{thread.id}}">Edit</a>
        <a href="/threadApp/threadDelete/{{thread.id}}">Delete</a>
        <a href="/threadApp/threadDownload/{{thread.id}}">Download Thread</a>
    </li>
    {% endif %}
    {% endfor %}
</ul>
<hr>
<h3>Private Invited Posts</h3>
<ul>
    {% for thread in threadsInv %}
    {% if thread.thread_Exposer == "private" %}
    <li>
        <a href="/threadApp/details/{{thread.id}}">{{thread.thread_Name}}</a>
    </li>
    {% endif %}
    {% endfor %}
</ul>
<hr>

<a href="/threadApp/">Back</a>

{% endblock %}